### ISSUE TITLE
api_keyはデフォルトで環境変数を使ってほしい

### ISSUE THREAD

**Issue by hatappi** [asonas/chatwork-ruby#11]
下記のREADME.mdのUSAGEにも記載されていますが、
本gemを使用する際にはまず初めに`ChatWork.api_key = "XXX"`を記載しないといけません。

この実装だとメソッドを使用する際に毎回定義してあげなければならないです。
使用するケースを考えると、トークンは環境変数にまたせて読み込ませるような下記のコードになるかと思います。
```ruby
ChatWork.api_key = ENV['CHATWORK_API_TOKEN']
```

本gemでは下記のコードのようにdefaultがnilになっているので、デフォルトを環境変数にしてあげるとよいかもしれません。
https://github.com/asonas/chatwork-ruby/blob/master/lib/chatwork.rb#L20

他のgemの実装などを見てみると例えばgoogleが出しているauthに使用するgemの[google-auth-library-ruby](https://github.com/google/google-auth-library-ruby)ではuserがoptionsとして認証情報を指定しなかった場合に下記のコードのように環境変数を指定するようにしています
https://github.com/google/google-auth-library-ruby/blob/master/lib/googleauth/user_refresh.rb#L61

**Comment by h-michael** [comment]
👍
