### ISSUE TITLE
APIConnectionError#status is always nil

### ISSUE THREAD

**Issue by jmatsu** [asonas/chatwork-ruby#67]
*I haven't seen APIConnectionError has happened on the production environment so this is not a bug report.*

APIConnectionError#status is always nil actually. This seems to be by design though, I would like to handle errors based on the HTTP status of the responses

https://github.com/asonas/chatwork-ruby/blob/aa753b165c1dea3fbe8f8cb692b737fc78debe62/lib/chatwork/chatwork_error.rb#L41

It sounds APIConnectionError happens iff a response from the Chatwork server is not a valid format. I'm unsure how frequent it has happened though, I think APIConnectionError must also have the *status* field because it's originally from HTTP requests, even if that's like an illegal case on the Chatwork domain. What do you think?

**Comment by sue445** [comment]
@jmatsu I fixed at #68 and released v0.12.1

**Comment by jmatsu** [comment]
Sure! Thank you for your quick fixing. 😍
