### ISSUE TITLE
refresh_token 

### ISSUE THREAD

**Issue by AriesVu** [asonas/chatwork-ruby#81]
I use API to send notification, but I don't know how long refresh_token is and how can I extend refresh_token expiration

**Comment by sue445** [comment]
Default expiration is 14 days, but you can make it indefinite using `offline_access` .

See https://download.chatwork.com/ChatWork_API_Documentation.pdf

**Comment by AriesVu** [comment]
if i set scope is offline_access then the access_token or refresh_token
will be indefinitely

Vào Th 3, 15 thg 3, 2022 vào lúc 12:21 Go Sueyoshi <
***@***.***> đã viết:
